MAPA_DESTINOS = {
    "001": ("Galeão", "Terminal Gentileza"),
    "006": ("Silvestre", "Castelo"),
    "007": ("Silvestre", "Central Do Brasil"),
    "010": ("Bairro De Fátima", "Central Do Brasil"),
    "10": ("Santa Cruz", "Terminal Alvorada"),
    "11": ("Santa Cruz", "Terminal Alvorada"),
    "12": ("Terminal Pingo D'Água", "Terminal Alvorada"),
    "13": ("Terminal Mato Alto", "Terminal Alvorada"),
    "14": ("Santa Eugênia", "Terminal Recreio"),
    "15": ("Terminal Curral Falso", "Terminal Alvorada"),
    "16": ("Magarça", "Terminal Alvorada"),
    "17": ("Campo Grande", "Santa Cruz"),
    "18": ("Pontal", "Terminal Jardim Oceânico"),
    "19": ("Terminal Pingo D'Água", "Salvador Allende"),
    "20": ("Santa Cruz", "Salvador Allende"),
    "22": ("Terminal Alvorada", "Terminal Jardim Oceânico"),
    "25": ("Terminal Mato Alto", "Terminal Alvorada"),
    "28": ("Terminal Pingo D'Água", "Terminal Curral Falso"),
    "31": ("Vicente De Carvalho", "Terminal Alvorada"),
    "35": ("Terminal Madureira", "Terminal Alvorada"),
    "40": ("Terminal Madureira", "Terminal Alvorada"),
    "41": ("Terminal Madureira", "Terminal Recreio"),
    "42": ("Galeão", "Madureira"),
    "43": ("Terminal Fundão", "Santa Efigênia"),
    "46": ("Penha", "Terminal Alvorada"),
    "50": ("Terminal Jardim Oceânico", "Terminal Centro Olímpico"),
    "51": ("Terminal Deodoro", "Terminal Recreio"),
    "52": ("Terminal Deodoro", "Terminal Alvorada"),
    "53": ("Terminal Sulacap", "Terminal Alvorada"),
    "54": ("Terminal Centro Olímpico", "Anil"),
    "60": ("Terminal Deodoro", "Terminal Gentileza"),
    "61": ("Terminal Deodoro", "Terminal Gentileza"),
    "67": ("Terminal Campo Grande", "Terminal Deodoro"),
    "68": ("Bangu", "Terminal Deodoro"),
    "70": ("Terminal Margaridas", "Terminal Gentileza"),
    "73": ("Terminal Margaridas", "Terminal Gentileza"),
    "80": ("Penha", "Terminal Gentileza"),
    "90": ("Terminal Fundão", "Terminal Gentileza"),
    "100": ("General Osório", "Central"),
    "104": ("São Conrado", "Terminal Gentileza"),
    "107": ("Central", "Urca"),
    "117": ("Central", "Cosme Velho"),
    "126": ("Méier", "Parque Piedade"),
    "127": ("Gávea", "Rodoviária"),
    "131": ("São Conrado", "Terminal Gentileza"),
    "132": ("Norte Shopping", "Copacabana"),
    "133": ("Largo Do Machado", "Terminal Gentileza"),
    "134": ("Central Do Brasil", "Leblon"),
    "135": ("Paula Matos", "Central Do Brasil"),
    "136": ("Terminal Gentileza", "Leme"),
    "138": ("Rocinha", "Leme"),
    "139": ("Saens Peña", "Gávea"),
    "140": ("Terminal Margaridas", "Méier"),
    "141": ("Terminal Margaridas", "Méier"),
    "142": ("Madureira", "Jardim América"),
    "143": ("Metrô Pavuna", "Terminal Margaridas"),
    "144": ("Metrô Vicente De Carvalho", "Terminal Margaridas"),
    "145": ("Metrô Vicente De Carvalho", "Terminal Margaridas"),
    "146": ("Metrô Vicente De Carvalho", "Terminal Margaridas"),
    "147": ("Metrô Pavuna", "Saens Peña"),
    "148": ("Terminal Margaridas", "Méier"),
    "149": ("Terminal Alvorada", "Metrô Botafogo"),
    "150": ("Grajaú", "Metrô Siqueira Campos"),
    "151": ("Grajaú", "Leblon"),
    "152": ("Circular Da Penha", "Largo Do Machado"),
    "153": ("Metrô São Cristóvão", "Metrô Siqueira Campos"),
    "154": ("Vila Isabel", "Leblon"),
    "160": ("Terminal Gentileza", "Leblon"),
    "161": ("Terminal Gentileza", "Ipanema"),
    "162": ("Terminal Gentileza", "Alto Gávea"),
    "165": ("Terminal Gentileza", "Cosme Velho"),
    "167": ("Terminal Gentileza", "Urca"),
    "169": ("Terminal Gentileza", "General Osório"),
    "201": ("Santa Alexandrina", "Castelo"),
    "202": ("Rio Comprido", "Castelo"),
    "209": ("Candelária", "Caju"),
    "210": ("Caju", "Candelária"),
    "217": ("Andaraí", "Carioca"),
    "220": ("Usina", "Candelária"),
    "229": ("Usina", "Castelo"),
    "232": ("Lins De Vasconcelos", "Castelo"),
    "238": ("Água Santa", "Castelo"),
    "239": ("Água Santa", "Passeio"),
    "247": ("Camarista Méier", "Passeio"),
    "249": ("Água Santa", "Carioca"),
    "254": ("Madureira", "Candelária"),
    "265": ("Marechal Hermes", "Castelo"),
    "275": ("Méier", "Candelária"),
    "277": ("Rocha Miranda", "Candelária"),
    "292": ("Engenho Da Rainha", "Castelo"),
    "296": ("Irajá", "Castelo"),
    "298": ("Acari", "Castelo"),
    "300": ("Terminal Sulacap", "Candelária"),
    "301": ("Terminal Gentileza", "Terminal Alvorada"),
    "302": ("Terminal Gentileza", "Terminal Alvorada"),
    "306": ("Praça Seca", "Castelo"),
    "311": ("Engenheiro Leal", "Candelária"),
    "312": ("Olaria", "Candelária"),
    "313": ("Penha", "Praça Tiradentes"),
    "315": ("Central", "Recreio Dos Bandeirantes"),
    "319": ("Terminal Alvorada", "Central Do Brasil"),
    "321": ("Bancários", "Castelo"),
    "323": ("Bananal", "Castelo"),
    "324": ("Ribeira", "Candelária"),
    "325": ("Ribeira", "Castelo"),
    "326": ("Bancários", "Candelária"),
    "327": ("Ribeira", "Castelo"),
    "328": ("Bananal", "Candelária"),
    "329": ("Bancários", "Candelária"),
    "335": ("Cordovil", "Tiradentes"),
    "338": ("Taquara", "Candelária"),
    "341": ("Taquara", "Candelária"),
    "342": ("Jardim América", "Castelo"),
    "343": ("Jardim Oceânico", "Candelária"),
    "348": ("Riocentro", "Candelária"),
    "349": ("Rocha Miranda", "Castelo"),
    "350": ("Irajá", "Castelo"),
    "352": ("Riocentro", "Candelária"),
    "353": ("Gardênia Azul", "Terminal Gentileza"),
    "355": ("Madureira", "Praça Tiradentes"),
    "361": ("Recreio Dos Bandeirantes", "Castelo"),
    "362": ("Honório Gurgel", "Castelo"),
    "363": ("Vila Valqueire", "Candelária"),
    "368": ("Riocentro", "Candelária"),
    "369": ("Bangu", "Candelária"),
    "371": ("Praça Seca", "Praça Tiradentes"),
    "378": ("Marechal Hermes", "Castelo"),
    "380": ("Curicica", "Candelária"),
    "383": ("Realengo", "Praça Da República"),
    "384": ("Pavuna", "Passeio"),
    "385": ("Village Pavuna", "Passeio"),
    "386": ("Anchieta", "Candelária"),
    "388": ("Santa Cruz", "Candelária"),
    "389": ("Vila Aliança", "Terminal Deodoro"),
    "390": ("Curicica", "Candelária"),
    "391": ("Padre Miguel", "Praça Da República"),
    "393": ("Bangu", "Candelária"),
    "397": ("Terminal Campo Grande", "Candelária"),
    "399": ("Pavuna", "Passeio"),
    "404": ("Caju", "Leblon"),
    "409": ("Saens Peña", "Horto"),
    "410": ("Saens Peña", "Gávea"),
    "415": ("Usina", "Leblon"),
    "416": ("Saens Peña", "Horto"),
    "422": ("Grajaú", "Cosme Velho"),
    "426": ("Usina", "Jardim De Alah"),
    "448": ("Furnas", "São Conrado"),
    "455": ("Méier", "Copacabana"),
    "457": ("Abolição", "Copacabana"),
    "461": ("São Cristóvão", "Ipanema"),
    "472": ("Triagem", "Leme"),
    "473": ("São Januário", "Lido"),
    "474": ("Jacaré", "Copacabana"),
    "476": ("Méier", "Leblon"),
    "483": ("Penha", "General Osório"),
    "484": ("Olaria", "General Osório"),
    "485": ("Fundão", "General Osório"),
    "486": ("Fundão", "General Osório"),
    "492": ("Bancários", "Prado Júnior"),
    "497": ("Penha", "Largo Do Machado"),
    "507": ("Silvestre", "Largo Do Machado"),
    "513": ("Urca", "Botafogo"),
    "518": ("Urca", "Botafogo"),
    "519": ("Urca", "Copacabana"),
    "539": ("Rocinha", "Leme"),
    "550": ("Tijuquinha", "Gávea"),
    "552": ("Terminal Alvorada", "Rio Sul"),
    "553": ("Recreio Dos Bandeirantes", "Rio Sul"),
    "554": ("Rio Sul", "Piabas"),
    "555": ("Rio Das Pedras", "Gávea"),
    "557": ("Rio Das Pedras", "Copacabana"),
    "565": ("Tanque", "Gávea"),
    "583": ("Cosme Velho", "Leblon"),
    "584": ("Cosme Velho", "Leblon"),
    "585": ("Largo Do Machado", "Jardim De Alah"),
    "600": ("Taquara", "Saens Peña"),
    "601": ("Santa Maria", "Saens Peña"),
    "603": ("Usina", "Saens Peña"),
    "606": ("Engenho De Dentro", "Terminal Gentileza"),
    "607": ("Cascadura", "Rio Comprido"),
    "608": ("Grajaú", "Saens Peña"),
    "610": ("Del Castilho", "Tanque"),
    "611": ("Camorim", "Del Castilho"),
    "613": ("Del Castilho", "Vargem Grande"),
    "614": ("Del Castilho", "Terminal Alvorada"),
    "616": ("Del Castilho", "Fundão"),
    "621": ("Penha", "Saens Peña"),
    "622": ("Penha", "Saens Peña"),
    "623": ("Penha", "Saens Peña"),
    "624": ("Mariópolis", "Praça Da Bandeira"),
    "625": ("Olaria", "Saens Peña"),
    "626": ("Saens Peña", "Muda"),
    "627": ("Inhaúma", "Saens Peña"),
    "628": ("Penha", "Nova América"),
    "629": ("Irajá", "Saens Peña"),
    "630": ("Penha", "Saens Peña"),
    "634": ("Bananal", "Saens Peña"),
    "635": ("Bananal", "Saens Peña"),
    "636": ("Merck", "Saens Peña"),
    "638": ("Marechal Hermes", "Saens Peña"),
    "639": ("Jardim América", "Saens Peña"),
    "645": ("Terminal Alvorada", "Saens Peña"),
    "650": ("Marechal Hermes", "Engenho Novo"),
    "651": ("Cascadura", "Méier"),
    "652": ("Cascadura", "Méier"),
    "653": ("Terminal Deodoro", "Méier"),
    "663": ("Méier", "Fundão"),
    "665": ("Pavuna", "Saens Peña"),
    "669": ("Pavuna", "Méier"),
    "678": ("Méier", "Vila Valqueire"),
    "679": ("Grotão", "Méier"),
    "687": ("Pavuna", "Méier"),
    "688": ("Méier", "Pavuna"),
    "691": ("Méier", "Terminal Alvorada"),
    "692": ("Méier", "Terminal Alvorada"),
    "693": ("Méier", "Terminal Alvorada"),
    "696": ("Méier", "Praia Do Dendê"),
    "711": ("Rocha Miranda", "Rio Comprido"),
    "712": ("Cascadura", "Irajá"),
    "721": ("Vila Cruzeiro", "Cascadura"),
    "731": ("Campo Grande", "Marechal Hermes"),
    "737": ("Santíssimo", "Cascadura"),
    "741": ("Terminal Sulacap", "Bangu"),
    "743": ("Terminal Sulacap", "Bangu"),
    "745": ("Bangu", "Cascadura"),
    "746": ("Jabour", "Cascadura"),
    "753": ("Santa Cruz", "Metrô Coelho Neto"),
    "754": ("Santa Cruz", "Terminal Deodoro"),
    "756": ("Santa Cruz", "Coelho Neto"),
    "757": ("Sepetiba", "Coelho Neto"),
    "759": ("Cesarão", "Coelho Neto"),
    "764": ("Catiri", "Terminal Deodoro"),
    "765": ("Mendanha", "Terminal Deodoro"),
    "766": ("Madureira", "Freguesia"),
    "770": ("Campo Grande", "Metrô Coelho Neto"),
    "771": ("Campo Grande", "Metrô Coelho Neto"),
    "774": ("Madureira", "Jardim América"),
    "775": ("Jardim América", "Madureira"),
    "777": ("Padre Miguel", "Madureira"),
    "778": ("Pavuna", "Cascadura"),
    "779": ("Metrô Pavuna", "Terminal Madureira"),
    "780": ("Metrô Pavuna", "Terminal Madureira"),
    "783": ("Terminal Deodoro", "Praça Seca"),
    "785": ("Cascadura", "Marechal Hermes"),
    "786": ("Terminal Campo Grande", "Cascadura"),
    "788": ("Terminal Campo Grande", "Terminal Deodoro"),
    "790": ("Campo Grande", "Cascadura"),
    "791": ("Padre Miguel", "Terminal Deodoro"),
    "793": ("Pavuna", "Terminal Sulacap"),
    "794": ("Bangu", "Cascadura"),
    "795": ("Pavuna", "Terminal Deodoro"),
    "796": ("Campo Grande", "Terminal Deodoro"),
    "798": ("Campo Grande", "Terminal Deodoro"),
    "799": ("Metrô Pavuna", "Bangu"),
    "801": ("Bangu", "Taquara"),
    "802": ("Terminal Campo Grande", "Bangu"),
    "803": ("Jabour", "Terminal Sulacap"),
    "804": ("Terminal Curral Falso", "Campo Grande"),
    "805": ("Terminal Alvorada", "Jardim Oceânico"),
    "807": ("Jesuítas", "Terminal Curral Falso"),
    "808": ("Salim", "Campo Grande"),
    "809": ("Sagrado Coração", "Santa Cruz"),
    "810": ("Pontal", "Terminal Taquara"),
    "812": ("Carobinha", "Bangu"),
    "817": ("Piabas", "Vargem Grande"),
    "819": ("Jardim Bangu", "Bangu"),
    "820": ("Rio Da Prata", "Terminal Mato Alto"),
    "821": ("Campo Grande", "Corcundinha"),
    "822": ("Campo Grande", "Corcundinha"),
    "825": ("Campo Grande", "Jesuítas"),
    "826": ("Carobinha", "Campo Grande"),
    "829": ("Gardênia Azul", "Freguesia"),
    "830": ("Pedregoso", "Campo Grande"),
    "831": ("Colônia", "Terminal Taquara"),
    "833": ("Conjunto Manguariba", "Campo Grande"),
    "834": ("Terminal Campo Grande", "Cabuçu De Baixo"),
    "835": ("Largo Do Correia", "Terminal Campo Grande"),
    "836": ("Rio Da Prata", "Terminal Campo Grande"),
    "837": ("Terminal Campo Grande", "Conjunto Da Marinha"),
    "838": ("Terminal Campo Grande", "Terminal Magarça"),
    "840": ("São Fernando", "Campo Grande"),
    "841": ("Campo Grande", "Inhoaíba"),
    "842": ("Paciência", "Campo Grande"),
    "843": ("Boa Esperança", "Campo Grande"),
    "844": ("Jardim Oceânico", "Barrinha"),
    "845": ("Cantagalo", "Terminal Campo Grande"),
    "846": ("Rio Da Prata", "Terminal Campo Grande"),
    "847": ("Rio Da Prata", "Terminal Campo Grande"),
    "848": ("Terminal Campo Grande", "Monte Santo"),
    "849": ("Base Aérea De Santa Cruz", "Campo Grande"),
    "850": ("Mendanha", "Campo Grande"),
    "851": ("Campo Grande", "Escola Amazonas"),
    "852": ("Terminal Campo Grande", "Pedra De Guaratiba"),
    "853": ("Terminal Mato Alto", "Terminal Deodoro"),
    "854": ("Terminal Campo Grande", "Ilha De Guaratiba"),
    "855": ("Terminal Magarça", "Terminal Deodoro"),
    "856": ("Capoeira Grande", "Terminal Campo Grande"),
    "857": ("Terminal Campo Grande", "Terminal Pingo D'Água"),
    "859": ("Covanca", "Largo Do Tanque"),
    "861": ("Rio Das Pedras", "Curicica"),
    "862": ("Rio Das Pedras", "Barra Da Tijuca"),
    "863": ("Rio Das Pedras", "Barra Da Tijuca"),
    "864": ("Terminal Campo Grande", "Bangu"),
    "865": ("Pau Da Fome", "Terminal Taquara"),
    "866": ("Terminal Campo Grande", "Terminal Pingo D'Água"),
    "867": ("Barra De Guaratiba", "Terminal Campo Grande"),
    "868": ("Urucânia", "Campo Grande"),
    "869": ("Santa Margarida", "Campo Grande"),
    "870": ("Sepetiba", "Santa Cruz"),
    "871": ("Terminal Pingo D'Água", "Cesarão"),
    "872": ("Praia De Sepetiba", "Terminal Mato Alto"),
    "878": ("Tanque", "Barra Da Tijuca"),
    "880": ("Rio Das Pedras", "Terminal Alvorada"),
    "881": ("Taquara", "Terminal Alvorada"),
    "883": ("Terminal Mato Alto", "Terminal Deodoro"),
    "884": ("Sepetiba", "Terminal Campo Grande"),
    "885": ("Terminal Mato Alto", "Santa Cruz"),
    "892": ("São Benedito", "Santa Cruz"),
    "893": ("Jardim Palmares", "Campo Grande"),
    "894": ("Terminal Campo Grande", "Jardim Moriçaba"),
    "895": ("Serrinha", "Campo Grande"),
    "897": ("Santa Cruz", "Terminal Pingo D'Água"),
    "898": ("Sepetiba", "Campo Grande"),
    "899": ("Barra De Guaratiba", "Terminal Recreio"),
    "900": ("Taquara", "Downtown"),
    "901": ("Bonsucesso", "Bananal"),
    "905": ("Bonsucesso", "Irajá"),
    "906": ("Jardim América", "Caju"),
    "908": ("Terminal Deodoro", "Bonsucesso"),
    "910": ("Bananal", "Irajá"),
    "913": ("Del Castilho", "Fundão"),
    "915": ("Bonsucesso", "Aeroporto Internacional Do Rj"),
    "917": ("Padre Miguel", "Bonsucesso"),
    "918": ("Jardim Violeta", "Terminal Deodoro"),
    "919": ("Pavuna", "Bonsucesso"),
    "920": ("Pavuna", "Bonsucesso"),
    "921": ("Bancários", "Ribeira"),
    "922": ("Tubiacanga", "Fundão"),
    "925": ("Bancários", "Aeroporto Internacional Do Rj"),
    "926": ("Senador Camará", "Penha"),
    "928": ("Marechal Hermes", "Bonsucesso"),
    "932": ("Gardênia Azul", "Tanque"),
    "940": ("Ramos", "Madureira"),
    "946": ("Pavuna", "Engenho Da Rainha"),
    "954": ("Terminal Taquara", "Recreio Dos Bandeirantes"),
    "961": ("Rio Das Pedras", "Recreio Dos Bandeirantes"),
    "975": ("Madureira", "Terminal Fundão"),
    "979": ("Terminal Madureira", "Terminal Fundão"),
    "987": ("Gardênia Azul", "Pechincha"),
    "990": ("Merck", "Joatinga"),
    "2110": ("Gardênia Azul", "Castelo"),
    "2111": ("Praça Seca", "Castelo"),
    "2112": ("Taquara", "Castelo"),
    "2114": ("Freguesia", "Castelo"),
    "2303": ("Cesarão", "Carioca"),
    "2305": ("Jardim América", "Castelo"),
    "2307": ("Jardim 7 De Abril", "Carioca"),
    "2308": ("Cosmos", "Carioca"),
    "2309": ("Urucânia", "Carioca"),
    "2310": ("Bangu", "Candelária"),
    "2334": ("Campo Grande", "Castelo"),
    "2335": ("Santa Cruz", "Castelo"),
    "2336": ("Campo Grande", "Castelo"),
    "2337": ("Santa Cruz", "Castelo"),
    "2338": ("Terminal Campo Grande", "Castelo"),
    "2339": ("Campo Grande", "Castelo"),
    "2342": ("Bananal", "Castelo"),
    "2343": ("Ribeira", "Castelo"),
    "2344": ("Bancários", "Castelo"),
    "2345": ("Vila Valqueire", "Castelo"),
    "2381": ("Pedra De Guaratiba", "Castelo"),
    "2383": ("Sepetiba", "Carioca"),
    "2613": ("Riocentro", "Metrô Del Castilho"),
    "2614": ("Terminal Alvorada", "Metrô Del Castilho"),
    "2802": ("Santa Cruz", "Barra Da Tijuca"),
    "2803": ("Vila Kennedy", "Terminal Alvorada"),
    "2804": ("Bangu", "Barra Da Tijuca"),
}
